server:
  port: 8083
spring:
  mail:
    host: smtp.qq.com
    ## 端口(不同邮箱端口不同)
    port: 587
    ## 协议
    protocol: smtp
    default-encoding: utf-8
    ## 发送者邮箱地址
    username: carl.ling7979@qq.com
    ## 授权码 (在邮箱开通服务时获取)
    password: ikjgqjnvtkjaeaef
    ## redis配置

  redis:
    host: 127.0.0.1
    port: 6379
    database: 2
    password: admin
    timeout: 10000ms
    lettuce:
      pool:
        # 最大连接数
        max-active: 1024
        # 最大连接阻塞等待时间 默认 -1
        max-wait: 10000ms
        # 最大空闲
        max-idle: 200
        # 最小空闲
        min-idle: 5

  ## rabbitmq配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        # 开启手工确认
        acknowledge-mode: manual